services:
  - type: web
    name: your-app-name # Замените на имя вашего приложения (без пробелов)
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn SiteClothes.wsgi:application" # Указывает на файл wsgi.py внутри папки SiteClothes
    plan: free # Обязательно для бесплатного тарифа
    healthCheckPath: /admin/login/ # Или любой другой путь, который будет доступен
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: your-app-db # Имя вашей базы данных на Render
          property: connectionString
      - key: SECRET_KEY
        generateValue: true # Сгенерировать случайный ключ
      - key: WEB_CONCURRENCY
        value: 4 # Количество рабочих процессов Gunicorn (для небольших приложений)

  - type: worker # Если у вас есть фоновые задачи (например, Celery)
    name: my-worker
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "celery -A SiteClothes worker -l info" # Убедитесь, что `SiteClothes` соответствует вашей папке с проектом
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: your-app-db
          property: connectionString

databases:
  - name: your-app-db # Имя вашей базы данных на Render
    plan: free # Обязательно для бесплатного тарифа