# Generated by Django 4.2.16 on 2024-10-25 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_author_book_bookinstance_genre_language_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='brend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Список брендов')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Список брендов',
            },
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Статус', 'verbose_name_plural': 'Статусы одежды'},
        ),
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Cтaтyc одежды'),
        ),
    ]
