# Generated by Django 4.2.16 on 2024-10-25 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_brend_alter_status_options_alter_status_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Мужская/Женская')),
            ],
            options={
                'verbose_name': 'Пол',
                'verbose_name_plural': 'Мужская/Женская',
            },
        ),
    ]
