# Generated by Django 4.2.16 on 2024-10-25 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Все размеры')),
            ],
            options={
                'verbose_name': 'Размер',
                'verbose_name_plural': 'Все размеры',
            },
        ),
        migrations.AlterModelOptions(
            name='gender',
            options={'verbose_name': 'Пол', 'verbose_name_plural': 'Мужское/Женское'},
        ),
        migrations.AlterField(
            model_name='brend',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Список брендов'),
        ),
        migrations.AlterField(
            model_name='gender',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Мужское/Женское'),
        ),
    ]
