# Generated by Django 4.2.16 on 2024-10-25 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_clothes_remove_book_author_remove_bookinstance_book_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clothes',
            options={'verbose_name': 'Одежду', 'verbose_name_plural': 'Вся одежда'},
        ),
        migrations.AddField(
            model_name='clothes',
            name='brendd',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.brend', verbose_name='Бренд'),
        ),
        migrations.RemoveField(
            model_name='clothes',
            name='catt',
        ),
        migrations.AddField(
            model_name='clothes',
            name='catt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.cat', verbose_name='Категория'),
        ),
    ]
