# Generated by Django 4.2.16 on 2024-10-25 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_gender_options_alter_clothes_brendd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes',
            name='genderr',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalog.gender', verbose_name='Для'),
            preserve_default=False,
        ),
    ]
