# Generated by Django 4.2.16 on 2024-10-25 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_clothes_genderr'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes',
            name='sizee',
            field=models.ManyToManyField(to='catalog.size', verbose_name='Размер'),
        ),
    ]
