# Generated by Django 4.2.16 on 2024-10-25 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_clothes_statuss'),
    ]

    operations = [
        migrations.CreateModel(
            name='color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Цвет')),
            ],
            options={
                'verbose_name': 'Цвет',
                'verbose_name_plural': 'Цвет',
            },
        ),
        migrations.CreateModel(
            name='material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Материал')),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Материал',
            },
        ),
        migrations.AlterField(
            model_name='size',
            name='name',
            field=models.IntegerField(max_length=20, verbose_name='Все размеры'),
        ),
        migrations.AddField(
            model_name='clothes',
            name='colorr',
            field=models.ManyToManyField(to='catalog.color', verbose_name='Цвет'),
        ),
        migrations.AddField(
            model_name='clothes',
            name='materiall',
            field=models.ManyToManyField(to='catalog.material', verbose_name='Материал'),
        ),
    ]
