# Generated by Django 4.2.16 on 2024-10-25 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_color_material_alter_size_name_clothes_colorr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='name',
            field=models.IntegerField(verbose_name='Все размеры'),
        ),
    ]
