# Generated by Django 4.2.16 on 2024-10-25 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_alter_size_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothes',
            name='colorr',
        ),
        migrations.RemoveField(
            model_name='clothes',
            name='materiall',
        ),
        migrations.DeleteModel(
            name='color',
        ),
        migrations.DeleteModel(
            name='material',
        ),
    ]
