# Generated by Django 4.2.16 on 2024-10-25 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_remove_clothes_colorr_remove_clothes_materiall_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='name',
            field=models.IntegerField(max_length=20, verbose_name='Все размеры'),
        ),
    ]
