# Generated by Django 4.2.16 on 2024-10-25 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_alter_size_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Введите размер'),
        ),
    ]
