# Generated by Django 4.2.16 on 2024-10-25 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_color_alter_brend_name_alter_cat_name_clothes_colorr'),
    ]

    operations = [
        migrations.CreateModel(
            name='material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Материал')),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Материал',
            },
        ),
        migrations.RemoveField(
            model_name='clothes',
            name='colorr',
        ),
        migrations.AddField(
            model_name='clothes',
            name='materiall',
            field=models.ManyToManyField(to='catalog.material', verbose_name='Материал'),
        ),
        migrations.AddField(
            model_name='clothes',
            name='colorr',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalog.color', verbose_name='Цвет'),
            preserve_default=False,
        ),
    ]
