# Generated by Django 4.2.16 on 2024-10-26 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_clothes_imgg'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes',
            name='summ',
            field=models.CharField(default=1, max_length=200, verbose_name='Стоимость'),
            preserve_default=False,
        ),
    ]
