# Generated by Django 4.2.16 on 2024-10-26 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_clothes_summ'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='summ',
            field=models.IntegerField(max_length=6, verbose_name='Стоимость'),
        ),
    ]
