# Generated by Django 4.2.16 on 2024-10-26 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_alter_clothes_summ'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='summ',
            field=models.IntegerField(verbose_name='Стоимость'),
        ),
    ]
