# Generated by Django 4.2.16 on 2024-10-26 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='phone_number',
        ),
    ]
