# Generated by Django 4.2.16 on 2024-10-26 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0026_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='summ',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость'),
        ),
    ]
