# Generated by Django 4.2.16 on 2024-10-26 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0027_alter_clothes_summ'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='statuss',
            field=models.BooleanField(default=True, verbose_name='В наличии'),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
