# Generated by Django 4.2.16 on 2024-10-26 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0028_alter_clothes_statuss_delete_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='slug',
            field=models.SlugField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clothes',
            name='slug',
            field=models.CharField(db_index=True, default=1, max_length=150, unique=True),
            preserve_default=False,
        ),
        migrations.AlterIndexTogether(
            name='clothes',
            index_together={('id', 'slug')},
        ),
    ]
