# Generated by Django 4.2.16 on 2024-10-26 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0029_cat_slug_clothes_slug_alter_clothes_index_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clothes',
            options={'ordering': ('title',), 'verbose_name': 'Одежду', 'verbose_name_plural': 'Вся одежда'},
        ),
        migrations.RemoveField(
            model_name='cat',
            name='slug',
        ),
        migrations.AlterField(
            model_name='clothes',
            name='slug',
            field=models.CharField(max_length=200, unique=True, verbose_name='Название'),
        ),
    ]
