# Generated by Django 4.2.16 on 2024-10-26 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0030_alter_clothes_options_remove_cat_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Категория')),
                ('slug', models.CharField(max_length=50, unique=True, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категорию',
                'verbose_name_plural': 'Категории',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Название')),
                ('slug', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='Название')),
                ('image', models.ImageField(blank=True, upload_to='image/', verbose_name='Фото')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость')),
                ('available', models.BooleanField(default=True, verbose_name='В наличии')),
                ('brendd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.brend', verbose_name='Бренд')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalog.category', verbose_name='Категория')),
                ('colorr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.color', verbose_name='Цвет')),
                ('genderr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.gender', verbose_name='Для')),
                ('materiall', models.ManyToManyField(to='catalog.material', verbose_name='Материал')),
                ('sizee', models.ManyToManyField(to='catalog.size', verbose_name='Размер')),
            ],
            options={
                'verbose_name': 'Одежду',
                'verbose_name_plural': 'Вся одежда',
                'ordering': ('name',),
                'index_together': {('id', 'slug')},
            },
        ),
        migrations.AlterIndexTogether(
            name='clothes',
            index_together=None,
        ),
        migrations.RemoveField(
            model_name='clothes',
            name='brendd',
        ),
        migrations.RemoveField(
            model_name='clothes',
            name='catt',
        ),
        migrations.RemoveField(
            model_name='clothes',
            name='colorr',
        ),
        migrations.RemoveField(
            model_name='clothes',
            name='genderr',
        ),
        migrations.RemoveField(
            model_name='clothes',
            name='materiall',
        ),
        migrations.RemoveField(
            model_name='clothes',
            name='sizee',
        ),
        migrations.DeleteModel(
            name='cat',
        ),
        migrations.DeleteModel(
            name='clothes',
        ),
    ]
