# Generated by Django 4.2.16 on 2024-10-26 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0031_category_product_alter_clothes_index_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brendd',
        ),
        migrations.RemoveField(
            model_name='product',
            name='colorr',
        ),
        migrations.RemoveField(
            model_name='product',
            name='genderr',
        ),
        migrations.RemoveField(
            model_name='product',
            name='materiall',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sizee',
        ),
        migrations.DeleteModel(
            name='brend',
        ),
        migrations.DeleteModel(
            name='color',
        ),
        migrations.DeleteModel(
            name='gender',
        ),
        migrations.DeleteModel(
            name='material',
        ),
        migrations.DeleteModel(
            name='size',
        ),
    ]
