# Generated by Django 4.2.16 on 2024-10-26 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0032_remove_product_brendd_remove_product_colorr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='brend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Бренд')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Список брендов',
            },
        ),
        migrations.CreateModel(
            name='cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категорию',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='clothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.CharField(max_length=200, unique=True, verbose_name='Название')),
                ('summ', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость')),
                ('statuss', models.BooleanField(default=True, verbose_name='В наличии')),
                ('imgg', models.ImageField(upload_to='image/', verbose_name='Фото')),
                ('brendd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.brend', verbose_name='Бренд')),
                ('catt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.cat', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Одежду',
                'verbose_name_plural': 'Вся одежда',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Цвет')),
            ],
            options={
                'verbose_name': 'Цвет',
                'verbose_name_plural': 'Цвет',
            },
        ),
        migrations.CreateModel(
            name='gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Для кого')),
            ],
            options={
                'verbose_name': 'Пол',
                'verbose_name_plural': 'Для кого',
            },
        ),
        migrations.CreateModel(
            name='material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Материал')),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Материал',
            },
        ),
        migrations.CreateModel(
            name='size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Введите размер')),
            ],
            options={
                'verbose_name': 'Размер',
                'verbose_name_plural': 'Все размеры',
            },
        ),
        migrations.AlterIndexTogether(
            name='product',
            index_together=None,
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AddField(
            model_name='clothes',
            name='colorr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.color', verbose_name='Цвет'),
        ),
        migrations.AddField(
            model_name='clothes',
            name='genderr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.gender', verbose_name='Для'),
        ),
        migrations.AddField(
            model_name='clothes',
            name='materiall',
            field=models.ManyToManyField(to='catalog.material', verbose_name='Материал'),
        ),
        migrations.AddField(
            model_name='clothes',
            name='sizee',
            field=models.ManyToManyField(to='catalog.size', verbose_name='Размер'),
        ),
        migrations.AlterIndexTogether(
            name='clothes',
            index_together={('id', 'slug')},
        ),
    ]
