# Generated by Django 4.2.16 on 2024-10-26 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0033_brend_cat_clothes_color_gender_material_size_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clothes',
            options={'verbose_name': 'Одежду', 'verbose_name_plural': 'Вся одежда'},
        ),
        migrations.AlterIndexTogether(
            name='clothes',
            index_together=set(),
        ),
    ]
