# Generated by Django 4.2.16 on 2024-10-26 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0034_alter_clothes_options_alter_clothes_index_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothes',
            name='slug',
        ),
    ]
