# Generated by Django 4.2.16 on 2024-10-27 10:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0035_remove_clothes_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes',
            name='slug',
            field=models.SlugField(default=uuid.uuid1),
        ),
    ]
