# Generated by Django 4.2.16 on 2024-10-27 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0038_remove_clothes_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('date_of_start', models.DateField()),
                ('date_of_end', models.DateField()),
            ],
        ),
    ]
