# Generated by Django 4.2.16 on 2024-10-27 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0039_artists'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Заполните наименование услуги', max_length=40, verbose_name='Наименование услуги')),
                ('price', models.CharField(help_text='укажите цену за услугу', max_length=15, verbose_name='Цена')),
                ('description', models.TextField(max_length=1000, verbose_name='Описание услуги')),
            ],
        ),
        migrations.DeleteModel(
            name='Artists',
        ),
    ]
