# Generated by Django 4.2.16 on 2024-10-28 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0042_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='newss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('text', models.CharField(max_length=1000, verbose_name='Текст статьи')),
            ],
            options={
                'verbose_name': 'Статью',
                'verbose_name_plural': 'Статья',
            },
        ),
        migrations.DeleteModel(
            name='news',
        ),
    ]
