# Generated by Django 4.2.16 on 2024-10-28 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0043_newss_delete_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='newss',
            name='img',
            field=models.ImageField(default=1, upload_to='image/', verbose_name='Фото'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clothes',
            name='summ',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Стоимость'),
        ),
    ]
