# Generated by Django 4.2.16 on 2024-10-28 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0044_newss_img_alter_clothes_summ'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newss',
            name='text',
            field=models.TextField(max_length=5000, verbose_name='Текст статьи'),
        ),
    ]
