# Generated by Django 4.2.16 on 2024-10-29 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0048_cartitem_product_delete_profile_cartitem_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='sizee',
            field=models.ManyToManyField(related_name='size', to='catalog.size', verbose_name='Размер'),
        ),
    ]
