# Generated by Django 4.2.16 on 2024-10-29 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0049_alter_clothes_sizee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.clothes'),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
