# Generated by Django 4.2.16 on 2024-10-29 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0050_alter_cartitem_product_delete_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes',
            name='dates',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
