# Generated by Django 4.2.16 on 2024-11-26 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0053_thread_alter_cartitem_product_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Пост', 'verbose_name_plural': 'Пост из форума'},
        ),
        migrations.AlterModelOptions(
            name='thread',
            options={'verbose_name': 'Тему', 'verbose_name_plural': 'Тема поста форума'},
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(verbose_name='Текст темы'),
        ),
        migrations.AlterField(
            model_name='post',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.thread', verbose_name='Название темы'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название темы'),
        ),
    ]
