# Generated by Django 4.2.16 on 2024-11-26 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0058_alter_userprofile_avatar_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
