# Generated by Django 4.2.16 on 2024-11-26 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0063_remove_userprofile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
        migrations.AlterField(
            model_name='newss',
            name='img',
            field=models.ImageField(help_text='Рекомендуется изображение формата 1x1', upload_to='image/', verbose_name='Фото'),
        ),
    ]
