# Generated by Django 4.2.16 on 2024-11-29 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0065_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='catalog_userprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50, unique='false', verbose_name='Название поста')),
            ],
        ),
    ]
