# Generated by Django 4.2.16 on 2024-11-29 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0066_catalog_userprofile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='catalog_userprofile',
            new_name='userprofile',
        ),
    ]
