# Generated by Django 4.2.16 on 2024-11-29 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0067_rename_catalog_userprofile_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userprofile',
        ),
    ]
