# Generated by Django 4.2.16 on 2024-11-29 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0068_delete_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
