# Generated by Django 4.2.16 on 2024-11-29 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0070_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='dates',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Название поста'),
        ),
    ]
