# Generated by Django 4.2.16 on 2024-11-29 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0073_post_info_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_info',
            name='text',
            field=models.TextField(max_length=5000, verbose_name='Текст сообщения'),
        ),
    ]
