# Generated by Django 4.2.16 on 2024-11-29 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0074_alter_post_info_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post_info',
            name='user',
        ),
        migrations.AlterField(
            model_name='post_info',
            name='text',
            field=models.CharField(max_length=2000, verbose_name='Текст сообщения'),
        ),
    ]
