# Generated by Django 4.2.16 on 2024-11-29 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0076_post_info_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post_info',
            name='user',
        ),
    ]
