# Generated by Django 4.2.16 on 2024-12-05 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0080_comment_topic_alter_post_options_remove_post_dates_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='description',
        ),
    ]
