# Generated by Django 4.2.16 on 2024-12-07 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0081_remove_topic_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='topic',
        ),
    ]
