# Generated by Django 4.2.16 on 2024-12-14 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0085_alter_comment_options_alter_post_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='dates',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
