# Generated by Django 4.2.16 on 2024-12-14 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0086_post_dates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='dates',
        ),
    ]
