# Generated by Django 4.2.16 on 2025-06-04 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0089_promocode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocode',
            name='active',
        ),
        migrations.RemoveField(
            model_name='promocode',
            name='discount',
        ),
        migrations.AddField(
            model_name='promocode',
            name='discount_percentage',
            field=models.IntegerField(default=0, verbose_name='Процент скидки'),
        ),
        migrations.AddField(
            model_name='promocode',
            name='valid_until',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Действует до'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Кодовое слово'),
        ),
    ]
