# Generated by Django 4.2.16 on 2025-06-04 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0090_remove_promocode_active_remove_promocode_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Активность'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='discount_percentage',
            field=models.PositiveSmallIntegerField(verbose_name='Процент скидки'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='valid_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Действует до'),
        ),
    ]
