# Generated by Django 4.2.16 on 2025-06-05 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0091_promocode_active_alter_promocode_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocode',
            name='valid_until',
        ),
        migrations.AddField(
            model_name='promocode',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Срок действия'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Процент скидки'),
        ),
    ]
