# Generated by Django 4.2.16 on 2025-06-05 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0092_remove_promocode_valid_until_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocode',
            name='expiration_date',
        ),
    ]
