# Generated by Django 4.2.16 on 2025-06-05 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0093_remove_promocode_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='discount_percentage',
            field=models.IntegerField(default=0, verbose_name='Процент скидки'),
        ),
    ]
