# Generated by Django 4.2.16 on 2025-06-05 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0094_alter_promocode_discount_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='summ',
            field=models.IntegerField(verbose_name='Стоимость'),
        ),
    ]
