# Generated by Django 4.2.16 on 2025-06-05 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0095_alter_clothes_summ'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='max_discount_amount',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Максимальная сумма скидки'),
        ),
    ]
