# Generated by Django 4.2.16 on 2025-06-05 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0096_promocode_max_discount_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes',
            name='description',
            field=models.CharField(max_length=500, null=True, verbose_name='Описание'),
        ),
    ]
