# Generated by Django 4.2.16 on 2025-06-05 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0097_clothes_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Страна производитель')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Список стран',
            },
        ),
        migrations.AddField(
            model_name='clothes',
            name='countryy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.country', verbose_name='Страна производитель'),
        ),
    ]
