# Generated by Django 5.2.1 on 2025-06-07 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0103_remove_order_delivery_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('processing', 'Собирается'), ('shipped', 'Готов к выдаче'), ('delivered', 'Выдан'), ('cancelled', 'Отменен')], default='processing', max_length=20, verbose_name='Статус заказа'),
        ),
    ]
