# Generated by Django 5.2.1 on 2025-06-07 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0104_alter_order_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={},
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Количество на складе')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.clothes', verbose_name='Товар')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.size', verbose_name='Размер')),
            ],
            options={
                'verbose_name': 'Складской остаток',
                'verbose_name_plural': 'Складские остатки',
                'unique_together': {('product', 'size')},
            },
        ),
        migrations.AddField(
            model_name='clothes',
            name='available_sizes',
            field=models.ManyToManyField(through='catalog.Stock', through_fields=('product', 'size'), to='catalog.size', verbose_name='Доступные размеры и их количество'),
        ),
    ]
