# Generated by Django 5.2.1 on 2025-06-08 08:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0106_remove_post_author_remove_post_topic_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
            ],
            options={
                'verbose_name': 'Заголовок категории форума',
                'verbose_name_plural': 'Заголовок категории форума',
            },
        ),
        migrations.AlterModelOptions(
            name='brend',
            options={'verbose_name': 'Бренд', 'verbose_name_plural': 'Список брендов'},
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'Корзину', 'verbose_name_plural': 'Корзина'},
        ),
        migrations.AlterModelOptions(
            name='cat',
            options={'verbose_name': 'Категорию', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='clothes',
            options={'verbose_name': 'Одежду', 'verbose_name_plural': 'Вся одежда'},
        ),
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name': 'Цвет', 'verbose_name_plural': 'Цвет'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Страна', 'verbose_name_plural': 'Список стран'},
        ),
        migrations.AlterModelOptions(
            name='gender',
            options={'verbose_name': 'Пол', 'verbose_name_plural': 'Для кого'},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'verbose_name': 'Материал', 'verbose_name_plural': 'Материал'},
        ),
        migrations.AlterModelOptions(
            name='newss',
            options={'verbose_name': 'Статью', 'verbose_name_plural': 'Статья'},
        ),
        migrations.AlterModelOptions(
            name='size',
            options={'verbose_name': 'Размер', 'verbose_name_plural': 'Все размеры'},
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='clothes',
            name='old_price',
        ),
        migrations.AddField(
            model_name='clothes',
            name='available_sizes',
            field=models.ManyToManyField(through='catalog.Stock', through_fields=('product', 'size'), to='catalog.size', verbose_name='Доступные размеры и их количество'),
        ),
        migrations.AddField(
            model_name='clothes',
            name='sizee',
            field=models.ManyToManyField(related_name='size', to='catalog.size', verbose_name='Размер'),
        ),
        migrations.AlterField(
            model_name='brend',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.size', verbose_name='Размер'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='brendd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.brend', verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='catt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.cat', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='colorr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.color', verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='countryy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.country', verbose_name='Страна производитель'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='dates',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='description',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='genderr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.gender', verbose_name='Для'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='imgg',
            field=models.ImageField(upload_to='image/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='statuss',
            field=models.BooleanField(default=True, verbose_name='В наличии'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='summ',
            field=models.IntegerField(verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Страна производитель'),
        ),
        migrations.AlterField(
            model_name='gender',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Для кого'),
        ),
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Материал'),
        ),
        migrations.AlterField(
            model_name='newss',
            name='dates',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='newss',
            name='img',
            field=models.ImageField(help_text='Рекомендуется изображение формата 1x1', upload_to='image/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='newss',
            name='text',
            field=models.TextField(max_length=5000, verbose_name='Текст статьи'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.IntegerField(default=0, verbose_name='Итоговая стоимость'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.IntegerField(verbose_name='Цена за единицу'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='size',
            field=models.CharField(max_length=20, verbose_name='Размер'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Активность'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='discount_percentage',
            field=models.IntegerField(default=0, verbose_name='Процент скидки'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='max_discount_amount',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Максимальная сумма скидки'),
        ),
        migrations.AlterField(
            model_name='size',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Введите размер'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.clothes', verbose_name='Товар'),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок поста')),
                ('body', models.TextField(blank=True, null=True, verbose_name='Текст поста')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('topic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.topic', verbose_name='Заголовок')),
            ],
            options={
                'verbose_name': 'Пост пользователя',
                'verbose_name_plural': 'Пост пользователя',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время')),
                ('body', models.TextField(verbose_name='Сообщение')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.post', verbose_name='Пост')),
            ],
            options={
                'verbose_name': 'Коментарии под посты',
                'verbose_name_plural': 'Коментарии под посты',
            },
        ),
    ]
